services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
    volumes:
      - .:/var/www/html

  db:
    image: postgres:12
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: atec
      POSTGRES_PASSWORD: atec
      POSTGRES_DB: games_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  angular-app:
    build:
      context: ./games_front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./games_front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    user: "front"


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./games_front/nginx.conf:/etc/nginx/nginx.conf
      - ./games_front/dist:/usr/share/nginx/html
    depends_on:
      - laravel-app
      - angular-app

volumes:
  postgres-data:
  node_modules:
    driver: local
