services:
  laravel-app:

    container_name: laravel-app
    image: juliocesarx/games-api.1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html

  db:
    container_name: postgres-db
    image: postgres:12
    environment:
      - POSTGRES_USER=atec
      - POSTGRES_PASSWORD=atec
      - POSTGRES_DB=games_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  angular-app:
    container_name: angular-app
    image: juliocesarx/games-front.1.0.0
    build:
      context: ./games_front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./games_front:/usr/src/app
    depends_on:
      - laravel-app

volumes:
  postgres-data:
